# Book settings
title: Geographic Data Science with PySAL and the PyData Stack
author: Sergio J. Rey, Daniel Arribas-bel, Levi J. Wolf
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: off
